### GET entry by date (yyyy-mm-dd)
GET http://localhost:3000/entry/day HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTQxMzQwNDMuOTAxLCJpYXQiOjE3MTQxMzA0NDN9.yBBF5hybkHxqWh5tcNft8nGAcZOa8j-TUQEkUKJaCbs

{
  "date": "2024-03-25"
}


### POST add day entry
POST http://localhost:3000/api/entry/day HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTI4NDM4NzYuMzksImlhdCI6MTcxMjg0MDI3Nn0.XVoTXg9XSIuU-xrj3fjZOEPxCTrNqHgqvW30nqTnMZk

{
 "fixed_blocks": {
    "date": "2024-03-26",
    "mood": 4,
    "emotions": {
      "happy": 0,
      "sad": 1,
      "grumpy": 1
    },
    "text": "Feeling good today",
    "period": 1
  },
  "icon_blocks": [],
  "number_blocks": []
}

### Get week data
GET http://localhost:3000/entry/week HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTQxMzQwNDMuOTAxLCJpYXQiOjE3MTQxMzA0NDN9.yBBF5hybkHxqWh5tcNft8nGAcZOa8j-TUQEkUKJaCbs

{
  "date": "2024-03-25"
}


### post week data
POST http://localhost:3000/entry/week/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTQxMzQwNDMuOTAxLCJpYXQiOjE3MTQxMzA0NDN9.yBBF5hybkHxqWh5tcNft8nGAcZOa8j-TUQEkUKJaCbs

{
  "date": "2024-03-25",
  "entryData": "Sample weekly entry text"
}
