### GET entry by date (yyyy-mm-dd)
GET http://localhost:3000/api/entry/day/2024-03-25 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTEzOTEwODMuNDg0LCJpYXQiOjE3MTEzODc0ODN9.mdeW1_-L92L1TzgpAZbyYO4tnrht4uqkBw8rOCGmJ24


### POST add entry
POST http://localhost:3000/api/entry/day HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTEzOTEwODMuNDg0LCJpYXQiOjE3MTEzODc0ODN9.mdeW1_-L92L1TzgpAZbyYO4tnrht4uqkBw8rOCGmJ24

{
 "fixed_blocks": {
    "date": "2024-03-25",
    "mood": 4,
    "emotions": {
      "happy": 0,
      "sad": 1,
      "grumpy": 1
    },
    "text": "Feeling good today",
    "period": 1
  },
  "icon_blocks": [],
  "number_blocks": []
}
