### GET entry by date (yyyy-mm-dd)
GET http://localhost:3000/entry/day?date=2024-03-25 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTkxMjUyOTEuMzgsImlhdCI6MTcxOTEyMTY5MX0.IJwp68O_h_GjY0zsmsXln12C1AXgMCla0YK-iyL-IEA

{
  "date": "2024-03-25"
}


### POST add day entry
POST http://localhost:3000/entry/day HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTg5MTcwNzEuODc3LCJpYXQiOjE3MTg5MTM0NzF9.tX-zGM21LbDCfTS0AlntCioH_NeGZr1g_PMt4mnUG3Y

{
  "date": "2024-03-25",
  "mood": 3,
  "period": 2,
  "emotions": {
    "exited": false,
    "relaxed": true,
    "proud": false,
    "hopefull": false,
    "happy": false,
    "lonely": false,
    "emo": false,
    "anxious": true,
    "sad": false,
    "angry": false,
    "tired": false
  },
  "weather": {
    "sunny": false,
    "windy": false,
    "rainy": true,
    "snowy": false,
    "cloudy": false
  },
  "sleep": 0,
  "water": 2,
  "text": "test"
}

### Get week data
GET http://localhost:3000/entry/week?date=2024-03-25 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTkxMzExOTMuOTU2LCJpYXQiOjE3MTkxMjc1OTN9.ysp_BAGHarBXyiOc87ulUc2lomCNGEXd2dyuUP3POaM

{
  "date": "2024-03-25"
}

### post week data
POST http://localhost:3000/entry/week/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTkxMzcxNzkuMDQ4LCJpYXQiOjE3MTkxMzM1Nzl9.NxWs9Gwj-scHc5MNeoJ0-Ia0R0hX7LxTaneDpPwNvg8

{
  "date": "2024-03-25",
  "entryData": "Sample weekly entry text"
}
