###
GET http://localhost:3000/api/evaluate/2024-03
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTI4NDM4NzYuMzksImlhdCI6MTcxMjg0MDI3Nn0.XVoTXg9XSIuU-xrj3fjZOEPxCTrNqHgqvW30nqTnMZk