### test in january
GET http://localhost:3000/api/evaluate/2024-01-01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTI4NTcwNzUuMjk1LCJpYXQiOjE3MTI4NTM0NzV9.6WDFLH12Bl_YRqcMs7z2foV1zkIy7BNZEP4GnQ7pSoA

### test for everything else
GET http://localhost:3000/api/evaluate/2024-04-15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTI5MjQzNDcuODQ5LCJpYXQiOjE3MTI5MjA3NDd9.jumkWT7n28VI5erVuIU2zVe1RH3FtvAa1KqottLISzg

### test for future
GET http://localhost:3000/api/evaluate/2024-05-01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTI5MzY1MzIuMTE3LCJpYXQiOjE3MTI5MzI5MzJ9.PfofIttjuz-tN1bIwngbjDdQg0CvuacpzyNW1U8mJ4w

### test for future but future like idk
GET http://localhost:3000/api/evaluate/2024-04-03
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTI5MjQzNDcuODQ5LCJpYXQiOjE3MTI5MjA3NDd9.jumkWT7n28VI5erVuIU2zVe1RH3FtvAa1KqottLISzg
