### test in january
GET http://localhost:3000/api/evaluate/2024-01-01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTI4NTcwNzUuMjk1LCJpYXQiOjE3MTI4NTM0NzV9.6WDFLH12Bl_YRqcMs7z2foV1zkIy7BNZEP4GnQ7pSoA

### test for everything else
GET http://localhost:3000/api/evaluate/2024-04-15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTI5MTE1NjIuMDQyLCJpYXQiOjE3MTI5MDc5NjJ9.U4FpeSZ5RtxFW6D-bwdpQ8slM80slGgpOGjy5cppE3g

