###
PUT http://localhost:3000/api/settings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiam9obiJ9LCJleHAiOjE3MTE0MDQwNTEuOTUzLCJpYXQiOjE3MTE0MDA0NTF9.SPsGr-vbhXun0KW1hwI8ZZoUPbjq6w9ti4eTzwVSWKM

{
  "ThemeNR": 2,
  "entrySettings": {
    "fixed_blocks": {
      "date": "2024-03-25",
      "mood": 5,
      "emotions": {
        "exited": 1
      },
      "text": "Example entry",
      "period": 2
    },
    "icon_blocks": [],
    "number_blocks": []
  },
  "trackPeriod": true
}
